#!/usr/bin/env python3
"""snb_workflow.py — ShakeNBreak (SnB) workflow helper.

Does NOT wrap SnB's API. Instead it generates a config file with sensible
defaults and prints the exact snb-* CLI commands to run, so the agent (or
user) can copy-paste them. SnB handles its own logic; this just makes the
common path ergonomic.

Workflow stages:
  prep       → write snb_config.yaml + print `snb-generate` command
  submit     → print `snb-run` command (SLURM-aware)
  parse      → print `snb-parse && snb-analyse && snb-plot` chain
  regenerate → print `snb-regenerate` (cross-charge-state reuse)
  groundstate→ print `snb-groundstate` (extract lowest-energy structure)

Run `snb_workflow.py <stage> -h` for stage-specific options.
"""
from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path

# Default SnB parameters (from SnB v3.3 docs).
DEFAULTS = {
    # Distortion grid: 13 steps from -60% to +60% in 10% increments.
    # Bond_Distortion_-0.6 ... Bond_Distortion_+0.6, plus Unperturbed + Rattled.
    "distortion_increment": 0.1,
    "bond_distortions_range": [-0.6, 0.6],
    # Bond-distoration list (None = auto-grid from increment).
    "bond_distortions": None,
    # Oxidation states: agent MUST fill per host chemistry.
    "oxidation_states": {},
    # Code backend.
    "code": "VASP",
    # Analysis thresholds.
    "min_e_diff": 0.05,   # eV; energy-lowering detection threshold
    "min_dist": 0.2,      # Å; structural-difference threshold
    # Regenerate (cross-charge metastable propagation).
    "metastable": False,
    # Plotting.
    "plot_format": "png",
    "plot_units": "eV",
    "plot_colorbar": False,
    "plot_metric": "max_dist",
}

CONFIG_TEMPLATE = """\
# ShakeNBreak configuration — fill in oxidation_states before use.
# Generated by atom-adjust/snb_workflow.py

# Oxidation states of elements in the pristine host (REQUIRED).
# SnB uses these to determine the number of neighbours to distort.
# Example for CdTe: {{Cd: +2, Te: -2}}
oxidation_states: {oxidation_states_repr}

# Bond-distortion grid. With distortion_increment=0.1 and range [-0.6, +0.6]
# you get 13 distortion points + Unperturbed + Rattled = 15 structures.
# For harder/ionic/magnetic materials, narrow to [-0.4, +0.4] or use 0.2 step.
distortion_increment: {distortion_increment}
# bond_distortions: [-0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6]

# Local rattle (decays with distance from defect). Usually leave False — the
# default global rattle is recommended by SnB authors.
local_rattle: false

# Optional: restrict which neighbour elements to distort.
# distorted_elements:
#   {{defect_name: [element_symbol, ...]}}

# Optional: restrict which neighbour atom indices to distort (0-indexed).
# distorted_atoms:
#   {{defect_name: [idx, ...]}}

# Optional: custom dimer bond length (Å) for dimer distortions.
# dimer_bond_length: null

# Rattle parameters (hiphive mc_rattle). Defaults are auto from NN distance.
# stdev: null        # gaussian σ (Å); default = 0.1 × bulk NN distance
# d_min: null        # min allowed interatomic distance (Å); default = 0.8 × NN
# seed: 42
"""


def _emit_block(title: str, lines: list[str]) -> None:
    print(f"\n=== {title} ===", file=sys.stderr)
    for ln in lines:
        print(ln, file=sys.stderr)


def cmd_prep(args: argparse.Namespace) -> int:
    cfg_path = Path(args.config)
    if cfg_path.exists() and not args.force:
        print(f"error: {cfg_path} exists (use --force to overwrite)",
              file=sys.stderr)
        return 1
    cfg_text = CONFIG_TEMPLATE.format(
        oxidation_states_repr=repr(DEFAULTS["oxidation_states"]),
        distortion_increment=DEFAULTS["distortion_increment"],
    )
    cfg_path.write_text(cfg_text)
    print(f"wrote {cfg_path}", file=sys.stderr)

    cmds = [
        "# 1. Generate distorted structures + VASP inputs:",
        "snb-generate \\",
        f"  --defect {args.defect} \\",
        f"  --bulk {args.bulk} \\",
        f"  --code {DEFAULTS['code']} \\",
        f"  --config {cfg_path} \\",
        "  -v",
        "",
        "# 2. (optional) Custom INCAR overrides go in the config file under",
        "#    user_incar_settings, or pass --input_file INCAR",
    ]
    _emit_block("Next: generate distortions", cmds)
    return 0


def cmd_submit(args: argparse.Namespace) -> int:
    submit_cmd = args.submit_command
    cmds = [
        "# Submit all SnB distortion relaxations:",
        f"snb-run \\",
        f"  --submit-command {submit_cmd} \\",
        f"  --job-script {args.job_script} \\",
        "  -v",
        "",
        "# snb-run auto-handles restarts (EDWAV/EDDDAV/ZPOTRF errors renamed",
        "# to Bond_Distortion_X_HighEnergy and skipped).",
        "# Convergence criterion: dE < 2 meV AND > ionic steps left.",
    ]
    _emit_block("Next: submit relaxations", cmds)
    return 0


def cmd_parse(args: argparse.Namespace) -> int:
    colorbar_line = ""
    if DEFAULTS["plot_colorbar"]:
        colorbar_line = f"  --colorbar --metric {DEFAULTS['plot_metric']} \\"
    cmds = [
        "# 1. Parse energies to YAML per-defect:",
        f"snb-parse --code {args.code.lower()} -v",
        "",
        "# 2. Generate CSV with structural comparisons:",
        f"snb-analyse --code {args.code.lower()} \\",
        f"  --ref_struct Unperturbed -v",
        "",
        "# 3. Plot energy vs distortion (highlights energy-lowering reconstructions):",
        f"snb-plot \\",
        f"  --code {args.code.lower()} \\",
        f"  --min_energy {DEFAULTS['min_e_diff']} \\",
        f"  --format {DEFAULTS['plot_format']} \\",
        f"  --units {DEFAULTS['plot_units']}",
        colorbar_line,
        "",
        "# Review the plot: any distortion point lower than Unperturbed by",
        f"# > {DEFAULTS['min_e_diff']} eV is an energy-lowering reconstruction.",
    ]
    cmds = [c for c in cmds if c]  # drop empty strings
    _emit_block("Next: parse + analyse + plot", cmds)
    return 0


def cmd_regenerate(args: argparse.Namespace) -> int:
    meta = " --metastable" if args.metastable else ""
    cmds = [
        "# After identifying energy-lowering distortions in one charge state,",
        "# propagate them to OTHER charge states of the same defect:",
        f"snb-regenerate \\",
        f"  --code {args.code.lower()} \\",
        f"  --min_energy {DEFAULTS['min_e_diff']} \\",
        f"  --filename {args.filename}{meta}",
        "",
        "# This re-tests the winning distortions for every charge state,",
        "# catching negative-U behaviour (different ground state at different q).",
    ]
    _emit_block("Next: regenerate across charge states", cmds)
    return 0


def cmd_groundstate(args: argparse.Namespace) -> int:
    cmds = [
        "# Extract the lowest-energy structure for each defect into a folder",
        "# for the next-stage accurate relaxation (typically vasp_nkred_std):",
        f"snb-groundstate \\",
        f"  --directory {args.directory} \\",
        f"  --groundstate_filename {args.gs_filename} \\",
        f"  --structure_filename {args.struct_filename}",
        "",
        "# Standard doped workflow after this:",
        f"#   {args.directory}/  →  vasp_std  →  vasp_ncl (SOC)",
        "# NKRED reduces hybrid-DFT cost; SOC final singlepoint.",
    ]
    _emit_block("Next: extract ground-state structures", cmds)
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="snb_workflow.py",
        description="ShakeNBreak workflow helper (prints snb-* commands).",
    )
    sub = p.add_subparsers(dest="stage", required=True)

    pp = sub.add_parser("prep", help="write snb_config.yaml + print snb-generate cmd")
    pp.add_argument("--defect", required=True, help="defect structure file (POSCAR)")
    pp.add_argument("--bulk", required=True, help="bulk structure file (POSCAR)")
    pp.add_argument("--config", default="snb_config.yaml",
                    help="config file to write (default: snb_config.yaml)")
    pp.add_argument("--force", action="store_true", help="overwrite existing config")
    pp.set_defaults(func=cmd_prep)

    ps = sub.add_parser("submit", help="print snb-run command")
    ps.add_argument("--submit-command", default="sbatch",
                    help="scheduler submit command (default: sbatch)")
    ps.add_argument("--job-script", default="submit.sh",
                    help="job script filename (default: submit.sh)")
    ps.set_defaults(func=cmd_submit)

    pa = sub.add_parser("parse", help="print snb-parse + snb-analyse + snb-plot chain")
    pa.add_argument("--code", default="VASP",
                    choices=["VASP", "CP2K", "espresso", "CASTEP", "FHI-aims"])
    pa.set_defaults(func=cmd_parse)

    pr = sub.add_parser("regenerate", help="print snb-regenerate command")
    pr.add_argument("--code", default="VASP",
                    choices=["VASP", "CP2K", "espresso", "CASTEP", "FHI-aims"])
    pr.add_argument("--filename", default="CONTCAR",
                    help="relaxed structure filename (default: CONTCAR)")
    pr.add_argument("--metastable", action="store_true",
                    help="also propagate metastable (not just ground-state) distortions")
    pr.set_defaults(func=cmd_regenerate)

    pg = sub.add_parser("groundstate", help="print snb-groundstate command")
    pg.add_argument("--directory", default="vasp_nkred_std",
                    help="output subdirectory name (default: vasp_nkred_std)")
    pg.add_argument("--gs-filename", default="POSCAR",
                    help="ground-state filename (default: POSCAR)")
    pg.add_argument("--struct-filename", default="CONTCAR",
                    help="source structure filename (default: CONTCAR)")
    pg.set_defaults(func=cmd_groundstate)

    return p


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
