#!/usr/bin/env python3
"""CCD post-processing for vibedft.

Reads a CCD directory generated by vasp-input phase=ccd. Each image
directory must contain OSZICAR after VASP finishes. Energies are plotted versus
alpha from ccd_manifest.json.

Usage:
  python3 ccd_diagram.py /path/to/ccd --output ccd.png
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def read_e0(oszicar: Path) -> float | None:
    if not oszicar.exists():
        return None
    for line in reversed(oszicar.read_text(errors="ignore").splitlines()):
        if "E0=" in line:
            try:
                return float(line.split("E0=", 1)[1].split()[0])
            except (IndexError, ValueError):
                return None
    return None


def collect(ccd_dir: Path) -> tuple[list[float], list[float]]:
    manifest_path = ccd_dir / "ccd_manifest.json"
    if not manifest_path.exists():
        raise FileNotFoundError(f"Missing {manifest_path}")
    manifest = json.loads(manifest_path.read_text())
    alphas, energies = [], []
    for image in manifest.get("images", []):
        img_dir = Path(image["dir"])
        e0 = read_e0(img_dir / "OSZICAR")
        if e0 is None:
            continue
        alphas.append(float(image["alpha"]))
        energies.append(e0)
    return alphas, energies


def main():
    parser = argparse.ArgumentParser(description="Plot CCD alpha-energy curve")
    parser.add_argument("ccd_dir", help="CCD directory containing ccd_manifest.json")
    parser.add_argument("--output", default="ccd.png", help="Output PNG path")
    parser.add_argument("--title", default="Configuration coordinate diagram")
    args = parser.parse_args()

    ccd_dir = Path(args.ccd_dir)
    alphas, energies = collect(ccd_dir)
    if not alphas:
        raise SystemExit("No image energies found. Run VASP first and check OSZICAR files.")
    e0 = min(energies)
    rel = [e - e0 for e in energies]

    import matplotlib.pyplot as plt

    plt.figure(figsize=(6, 4))
    plt.plot(alphas, rel, "o-", lw=1.5)
    plt.xlabel("Interpolation alpha")
    plt.ylabel("Energy relative to minimum (eV)")
    plt.title(args.title)
    plt.tight_layout()
    plt.savefig(args.output, dpi=200)
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
